name: Deploy to Azure Functions for development

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'back/functions' # set this to the path to your function app project, defaults to the repository root
  project_name: losttamshun
  environment: dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - uses: Azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID_DEV }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET_DEV }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Change this to the required Python version

      - name: 'Install dependencies'
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        env:
          environment: dev
        with:
          app-name: ${{ env.project_name }}-${{ env.environment }}-functions
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_DEV }}
